=== ftorralbo/LMISGI-2026-FranciscoTorralbo/cifp.dtd
<!ELEMENT cifp (alumne+, professor+)>
<!ELEMENT alumne (nom,llinatges,dataNaixement?,correu?,telefon?,adreça?,dataMatricula,curs)>
<!ELEMENT professor (nom,llinatges,dataNaixement?,correu?,telefon?,adreça?,dataIncorporacio,departament,assignatura*)>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT llinatges (#PCDATA)>
<!ELEMENT dataNaixement (#PCDATA)>
<!ELEMENT correu (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT adreça (#PCDATA)>
<!ELEMENT dataMatricula (#PCDATA)>
<!ELEMENT curs EMPTY>
<!ELEMENT dataIncorporacio (#PCDATA)>
<!ELEMENT departament EMPTY>
<!ELEMENT assignatura (nomAssignatura,dataInici?,dataFinal?)>
<!ELEMENT nomAssignatura (#PCDATA)>
<!ELEMENT dataInici (#PCDATA)>
<!ELEMENT dataFinal (#PCDATA)>

<!ATTLIST curs
          valor (DAM | DAW | ASIX | SMX | SEIA | ER | AUT) #REQUIRED>
<!ATTLIST alumne id CDATA #REQUIRED>
<!ATTLIST professor id CDATA #REQUIRED>
<!ATTLIST departament valor (INFORMATICA | ELECTRICITAT | AUTOMOCIO) #REQUIRED>
<!ATTLIST assignatura id CDATA #REQUIRED>
<!ATTLIST nomAssignatura cicle (DAM | DAW | ASIX | SMX | SEIA | ER | AUT) #REQUIRED>   

<!--
NOTA:
Aunque el enunciado indica que los identificadores (id) son de tipo entero,
el lenguaje DTD no permite definir tipos de datos numéricos.
Por este motivo, los atributos id se han definido como CDATA y obligatorios.
En el documento XML, los valores de id se escriben como números enteros.
-->

<!--
DTD no permite restringir valores en el contenido de los elementos;
por ello curs se define como atributo enumerado. No hay enum como en XSD y se simulan con atributos
-->

=== ftorralbo/LMISGI-2026-FranciscoTorralbo/cifp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cifp SYSTEM "cifp.dtd">

<cifp>

  <alumne id="1">
    <nom>Joan</nom>
    <llinatges>Garcia Pérez</llinatges>
    <dataNaixement>2003-05-14</dataNaixement>
    <correu>joan.garcia@email.com</correu>
    <telefon>600123456</telefon>
    <adreça>Carrer Major 10</adreça>
    <dataMatricula>2023-09-15</dataMatricula>
    <curs valor="DAW"/>
  </alumne>

  <alumne id="2">
    <nom>Laura</nom>
    <llinatges>Martí Ferrer</llinatges>
    <dataMatricula>2022-09-20</dataMatricula>
    <curs valor="DAM"/>
  </alumne>

  <professor id="10">
    <nom>Maria</nom>
    <llinatges>López Serra</llinatges>
    <dataIncorporacio>2018-09-01</dataIncorporacio>
    <departament valor="INFORMATICA"/>

    <assignatura id="100">
      <nomAssignatura cicle="DAW">Programació</nomAssignatura>
      <dataInici>2024-09-15</dataInici>
      <dataFinal>2025-06-20</dataFinal>
    </assignatura>

    <assignatura id="101">
      <nomAssignatura cicle="DAM">Bases de Dades</nomAssignatura>
    </assignatura>

  </professor>

</cifp>
